# Generated by Django 5.1.1 on 2024-09-21 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_code', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.zone')),
            ],
        ),
    ]
