# Generated by Django 5.1.1 on 2024-09-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
