# Generated by Django 5.1.1 on 2024-09-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office360degree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='size_type',
            field=models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='ad',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office360degree.adsize'),
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office360degree.adtype'),
        ),
    ]
