# Generated by Django 5.1.1 on 2024-09-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office360degree', '0002_adsize_adtype_ad_size_type_ad_size_ad_ad_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('booking_description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='bookings/')),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office360degree.ad')),
            ],
        ),
    ]
