# Generated by Django 5.1.1 on 2024-09-21 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office360degree', '0003_booking'),
        ('owner', '0003_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='owner.zone'),
        ),
    ]
